<?php
function trial_page_attachements(array &$page)
{
  $page['#attached']['library'][] = 'trial/movie_css';
}

function trial_theme($existing, $type, $theme, $path) {
  return array(
    'actor_list' => array(
      'variables' => array('items' => array(), 'title' => '')
    ),
    'movie_list' => array(
      'variables' => array('items' => array(), 'title' => '')
    ),
    'movie_block_actor' => array(
      'variables' => array('items' => array(), 'title' => '')
    ),
    'trial_filter' => array(
      'render element' => 'form',
    ),
  );
}


?>
